package in.gov.mohua.ds.transit;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Header.proto

public final class HeaderOuterClass {
    private HeaderOuterClass() {}
    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }
  
    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
      registerAllExtensions(
          (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Header)
        com.google.protobuf.MessageOrBuilder {
  
      /**
       * <pre>
       * Version of the dataset.
       * </pre>
       *
       * <code>string version = 1;</code>
       * @return The version.
       */
      java.lang.String getVersion();
      /**
       * <pre>
       * Version of the dataset.
       * </pre>
       *
       * <code>string version = 1;</code>
       * @return The bytes for version.
       */
      com.google.protobuf.ByteString
          getVersionBytes();
  
      /**
       * <code>.Header.Incrementality incrementality = 2;</code>
       * @return The enum numeric value on the wire for incrementality.
       */
      int getIncrementalityValue();
      /**
       * <code>.Header.Incrementality incrementality = 2;</code>
       * @return The incrementality.
       */
      HeaderOuterClass.Header.Incrementality getIncrementality();
  
      /**
       * <pre>
       * This timestamp identifies the moment when the content of this feed has been
       * created (time at the server). In POSIX time (i.e., number of seconds since
       * January 1st 1970 00:00:00 UTC).
       * </pre>
       *
       * <code>uint64 timestamp = 3;</code>
       * @return The timestamp.
       */
      long getTimestamp();
  
      /**
       * <pre>
       * Publisher/Provider of the dataset.
       * </pre>
       *
       * <code>.Provider provider = 4;</code>
       * @return Whether the provider field is set.
       */
      boolean hasProvider();
      /**
       * <pre>
       * Publisher/Provider of the dataset.
       * </pre>
       *
       * <code>.Provider provider = 4;</code>
       * @return The provider.
       */
      HeaderOuterClass.Provider getProvider();
      /**
       * <pre>
       * Publisher/Provider of the dataset.
       * </pre>
       *
       * <code>.Provider provider = 4;</code>
       */
      HeaderOuterClass.ProviderOrBuilder getProviderOrBuilder();
    }
    /**
     * Protobuf type {@code Header}
     */
    public static final class Header extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Header)
        HeaderOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Header.newBuilder() to construct.
      private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Header() {
        version_ = "";
        incrementality_ = 0;
      }
  
      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Header();
      }
  
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
  
                version_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
  
                incrementality_ = rawValue;
                break;
              }
              case 24: {
  
                timestamp_ = input.readUInt64();
                break;
              }
              case 34: {
                HeaderOuterClass.Provider.Builder subBuilder = null;
                if (provider_ != null) {
                  subBuilder = provider_.toBuilder();
                }
                provider_ = input.readMessage(HeaderOuterClass.Provider.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(provider_);
                  provider_ = subBuilder.buildPartial();
                }
  
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeaderOuterClass.internal_static_Header_descriptor;
      }
  
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeaderOuterClass.internal_static_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeaderOuterClass.Header.class, HeaderOuterClass.Header.Builder.class);
      }
  
      /**
       * <pre>
       * Determines whether the current fetch is incremental.
       * </pre>
       *
       * Protobuf enum {@code Header.Incrementality}
       */
      public enum Incrementality
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>UNKNOWN = 0;</code>
         */
        UNKNOWN(0),
        /**
         * <code>FULL_DATASET = 1;</code>
         */
        FULL_DATASET(1),
        /**
         * <code>DIFFERENTIAL = 2;</code>
         */
        DIFFERENTIAL(2),
        UNRECOGNIZED(-1),
        ;
  
        /**
         * <code>UNKNOWN = 0;</code>
         */
        public static final int UNKNOWN_VALUE = 0;
        /**
         * <code>FULL_DATASET = 1;</code>
         */
        public static final int FULL_DATASET_VALUE = 1;
        /**
         * <code>DIFFERENTIAL = 2;</code>
         */
        public static final int DIFFERENTIAL_VALUE = 2;
  
  
        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }
  
        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Incrementality valueOf(int value) {
          return forNumber(value);
        }
  
        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static Incrementality forNumber(int value) {
          switch (value) {
            case 0: return UNKNOWN;
            case 1: return FULL_DATASET;
            case 2: return DIFFERENTIAL;
            default: return null;
          }
        }
  
        public static com.google.protobuf.Internal.EnumLiteMap<Incrementality>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            Incrementality> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Incrementality>() {
                public Incrementality findValueByNumber(int number) {
                  return Incrementality.forNumber(number);
                }
              };
  
        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return HeaderOuterClass.Header.getDescriptor().getEnumTypes().get(0);
        }
  
        private static final Incrementality[] VALUES = values();
  
        public static Incrementality valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }
  
        private final int value;
  
        private Incrementality(int value) {
          this.value = value;
        }
  
        // @@protoc_insertion_point(enum_scope:Header.Incrementality)
      }
  
      public static final int VERSION_FIELD_NUMBER = 1;
      private volatile java.lang.Object version_;
      /**
       * <pre>
       * Version of the dataset.
       * </pre>
       *
       * <code>string version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Version of the dataset.
       * </pre>
       *
       * <code>string version = 1;</code>
       * @return The bytes for version.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
  
      public static final int INCREMENTALITY_FIELD_NUMBER = 2;
      private int incrementality_;
      /**
       * <code>.Header.Incrementality incrementality = 2;</code>
       * @return The enum numeric value on the wire for incrementality.
       */
      @java.lang.Override public int getIncrementalityValue() {
        return incrementality_;
      }
      /**
       * <code>.Header.Incrementality incrementality = 2;</code>
       * @return The incrementality.
       */
      @java.lang.Override public HeaderOuterClass.Header.Incrementality getIncrementality() {
        @SuppressWarnings("deprecation")
        HeaderOuterClass.Header.Incrementality result = HeaderOuterClass.Header.Incrementality.valueOf(incrementality_);
        return result == null ? HeaderOuterClass.Header.Incrementality.UNRECOGNIZED : result;
      }
  
      public static final int TIMESTAMP_FIELD_NUMBER = 3;
      private long timestamp_;
      /**
       * <pre>
       * This timestamp identifies the moment when the content of this feed has been
       * created (time at the server). In POSIX time (i.e., number of seconds since
       * January 1st 1970 00:00:00 UTC).
       * </pre>
       *
       * <code>uint64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
  
      public static final int PROVIDER_FIELD_NUMBER = 4;
      private HeaderOuterClass.Provider provider_;
      /**
       * <pre>
       * Publisher/Provider of the dataset.
       * </pre>
       *
       * <code>.Provider provider = 4;</code>
       * @return Whether the provider field is set.
       */
      @java.lang.Override
      public boolean hasProvider() {
        return provider_ != null;
      }
      /**
       * <pre>
       * Publisher/Provider of the dataset.
       * </pre>
       *
       * <code>.Provider provider = 4;</code>
       * @return The provider.
       */
      @java.lang.Override
      public HeaderOuterClass.Provider getProvider() {
        return provider_ == null ? HeaderOuterClass.Provider.getDefaultInstance() : provider_;
      }
      /**
       * <pre>
       * Publisher/Provider of the dataset.
       * </pre>
       *
       * <code>.Provider provider = 4;</code>
       */
      @java.lang.Override
      public HeaderOuterClass.ProviderOrBuilder getProviderOrBuilder() {
        return getProvider();
      }
  
      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;
  
        memoizedIsInitialized = 1;
        return true;
      }
  
      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getVersionBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
        }
        if (incrementality_ != HeaderOuterClass.Header.Incrementality.UNKNOWN.getNumber()) {
          output.writeEnum(2, incrementality_);
        }
        if (timestamp_ != 0L) {
          output.writeUInt64(3, timestamp_);
        }
        if (provider_ != null) {
          output.writeMessage(4, getProvider());
        }
        unknownFields.writeTo(output);
      }
  
      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;
  
        size = 0;
        if (!getVersionBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
        }
        if (incrementality_ != HeaderOuterClass.Header.Incrementality.UNKNOWN.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, incrementality_);
        }
        if (timestamp_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(3, timestamp_);
        }
        if (provider_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, getProvider());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }
  
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof HeaderOuterClass.Header)) {
          return super.equals(obj);
        }
        HeaderOuterClass.Header other = (HeaderOuterClass.Header) obj;
  
        if (!getVersion()
            .equals(other.getVersion())) return false;
        if (incrementality_ != other.incrementality_) return false;
        if (getTimestamp()
            != other.getTimestamp()) return false;
        if (hasProvider() != other.hasProvider()) return false;
        if (hasProvider()) {
          if (!getProvider()
              .equals(other.getProvider())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }
  
      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
        hash = (37 * hash) + INCREMENTALITY_FIELD_NUMBER;
        hash = (53 * hash) + incrementality_;
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
        if (hasProvider()) {
          hash = (37 * hash) + PROVIDER_FIELD_NUMBER;
          hash = (53 * hash) + getProvider().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }
  
      public static HeaderOuterClass.Header parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderOuterClass.Header parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderOuterClass.Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderOuterClass.Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderOuterClass.Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderOuterClass.Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderOuterClass.Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static HeaderOuterClass.Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static HeaderOuterClass.Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static HeaderOuterClass.Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static HeaderOuterClass.Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static HeaderOuterClass.Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
  
      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(HeaderOuterClass.Header prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }
  
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Header)
          HeaderOuterClass.HeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return HeaderOuterClass.internal_static_Header_descriptor;
        }
  
        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return HeaderOuterClass.internal_static_Header_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  HeaderOuterClass.Header.class, HeaderOuterClass.Header.Builder.class);
        }
  
        // Construct using HeaderOuterClass.Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
  
        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          version_ = "";
  
          incrementality_ = 0;
  
          timestamp_ = 0L;
  
          if (providerBuilder_ == null) {
            provider_ = null;
          } else {
            provider_ = null;
            providerBuilder_ = null;
          }
          return this;
        }
  
        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return HeaderOuterClass.internal_static_Header_descriptor;
        }
  
        @java.lang.Override
        public HeaderOuterClass.Header getDefaultInstanceForType() {
          return HeaderOuterClass.Header.getDefaultInstance();
        }
  
        @java.lang.Override
        public HeaderOuterClass.Header build() {
          HeaderOuterClass.Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
  
        @java.lang.Override
        public HeaderOuterClass.Header buildPartial() {
          HeaderOuterClass.Header result = new HeaderOuterClass.Header(this);
          result.version_ = version_;
          result.incrementality_ = incrementality_;
          result.timestamp_ = timestamp_;
          if (providerBuilder_ == null) {
            result.provider_ = provider_;
          } else {
            result.provider_ = providerBuilder_.build();
          }
          onBuilt();
          return result;
        }
  
        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof HeaderOuterClass.Header) {
            return mergeFrom((HeaderOuterClass.Header)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
  
        public Builder mergeFrom(HeaderOuterClass.Header other) {
          if (other == HeaderOuterClass.Header.getDefaultInstance()) return this;
          if (!other.getVersion().isEmpty()) {
            version_ = other.version_;
            onChanged();
          }
          if (other.incrementality_ != 0) {
            setIncrementalityValue(other.getIncrementalityValue());
          }
          if (other.getTimestamp() != 0L) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasProvider()) {
            mergeProvider(other.getProvider());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }
  
        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }
  
        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          HeaderOuterClass.Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (HeaderOuterClass.Header) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
  
        private java.lang.Object version_ = "";
        /**
         * <pre>
         * Version of the dataset.
         * </pre>
         *
         * <code>string version = 1;</code>
         * @return The version.
         */
        public java.lang.String getVersion() {
          java.lang.Object ref = version_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            version_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Version of the dataset.
         * </pre>
         *
         * <code>string version = 1;</code>
         * @return The bytes for version.
         */
        public com.google.protobuf.ByteString
            getVersionBytes() {
          java.lang.Object ref = version_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            version_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Version of the dataset.
         * </pre>
         *
         * <code>string version = 1;</code>
         * @param value The version to set.
         * @return This builder for chaining.
         */
        public Builder setVersion(
            java.lang.String value) {
          if (value == null) {
      throw new NullPointerException();
    }
    
          version_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Version of the dataset.
         * </pre>
         *
         * <code>string version = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearVersion() {
          
          version_ = getDefaultInstance().getVersion();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Version of the dataset.
         * </pre>
         *
         * <code>string version = 1;</code>
         * @param value The bytes for version to set.
         * @return This builder for chaining.
         */
        public Builder setVersionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
      throw new NullPointerException();
    }
    checkByteStringIsUtf8(value);
          
          version_ = value;
          onChanged();
          return this;
        }
  
        private int incrementality_ = 0;
        /**
         * <code>.Header.Incrementality incrementality = 2;</code>
         * @return The enum numeric value on the wire for incrementality.
         */
        @java.lang.Override public int getIncrementalityValue() {
          return incrementality_;
        }
        /**
         * <code>.Header.Incrementality incrementality = 2;</code>
         * @param value The enum numeric value on the wire for incrementality to set.
         * @return This builder for chaining.
         */
        public Builder setIncrementalityValue(int value) {
          
          incrementality_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.Header.Incrementality incrementality = 2;</code>
         * @return The incrementality.
         */
        @java.lang.Override
        public HeaderOuterClass.Header.Incrementality getIncrementality() {
          @SuppressWarnings("deprecation")
          HeaderOuterClass.Header.Incrementality result = HeaderOuterClass.Header.Incrementality.valueOf(incrementality_);
          return result == null ? HeaderOuterClass.Header.Incrementality.UNRECOGNIZED : result;
        }
        /**
         * <code>.Header.Incrementality incrementality = 2;</code>
         * @param value The incrementality to set.
         * @return This builder for chaining.
         */
        public Builder setIncrementality(HeaderOuterClass.Header.Incrementality value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          incrementality_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.Header.Incrementality incrementality = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearIncrementality() {
          
          incrementality_ = 0;
          onChanged();
          return this;
        }
  
        private long timestamp_ ;
        /**
         * <pre>
         * This timestamp identifies the moment when the content of this feed has been
         * created (time at the server). In POSIX time (i.e., number of seconds since
         * January 1st 1970 00:00:00 UTC).
         * </pre>
         *
         * <code>uint64 timestamp = 3;</code>
         * @return The timestamp.
         */
        @java.lang.Override
        public long getTimestamp() {
          return timestamp_;
        }
        /**
         * <pre>
         * This timestamp identifies the moment when the content of this feed has been
         * created (time at the server). In POSIX time (i.e., number of seconds since
         * January 1st 1970 00:00:00 UTC).
         * </pre>
         *
         * <code>uint64 timestamp = 3;</code>
         * @param value The timestamp to set.
         * @return This builder for chaining.
         */
        public Builder setTimestamp(long value) {
          
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * This timestamp identifies the moment when the content of this feed has been
         * created (time at the server). In POSIX time (i.e., number of seconds since
         * January 1st 1970 00:00:00 UTC).
         * </pre>
         *
         * <code>uint64 timestamp = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearTimestamp() {
          
          timestamp_ = 0L;
          onChanged();
          return this;
        }
  
        private HeaderOuterClass.Provider provider_;
        private com.google.protobuf.SingleFieldBuilderV3<
            HeaderOuterClass.Provider, HeaderOuterClass.Provider.Builder, HeaderOuterClass.ProviderOrBuilder> providerBuilder_;
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         * @return Whether the provider field is set.
         */
        public boolean hasProvider() {
          return providerBuilder_ != null || provider_ != null;
        }
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         * @return The provider.
         */
        public HeaderOuterClass.Provider getProvider() {
          if (providerBuilder_ == null) {
            return provider_ == null ? HeaderOuterClass.Provider.getDefaultInstance() : provider_;
          } else {
            return providerBuilder_.getMessage();
          }
        }
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         */
        public Builder setProvider(HeaderOuterClass.Provider value) {
          if (providerBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            provider_ = value;
            onChanged();
          } else {
            providerBuilder_.setMessage(value);
          }
  
          return this;
        }
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         */
        public Builder setProvider(
            HeaderOuterClass.Provider.Builder builderForValue) {
          if (providerBuilder_ == null) {
            provider_ = builderForValue.build();
            onChanged();
          } else {
            providerBuilder_.setMessage(builderForValue.build());
          }
  
          return this;
        }
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         */
        public Builder mergeProvider(HeaderOuterClass.Provider value) {
          if (providerBuilder_ == null) {
            if (provider_ != null) {
              provider_ =
                HeaderOuterClass.Provider.newBuilder(provider_).mergeFrom(value).buildPartial();
            } else {
              provider_ = value;
            }
            onChanged();
          } else {
            providerBuilder_.mergeFrom(value);
          }
  
          return this;
        }
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         */
        public Builder clearProvider() {
          if (providerBuilder_ == null) {
            provider_ = null;
            onChanged();
          } else {
            provider_ = null;
            providerBuilder_ = null;
          }
  
          return this;
        }
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         */
        public HeaderOuterClass.Provider.Builder getProviderBuilder() {
          
          onChanged();
          return getProviderFieldBuilder().getBuilder();
        }
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         */
        public HeaderOuterClass.ProviderOrBuilder getProviderOrBuilder() {
          if (providerBuilder_ != null) {
            return providerBuilder_.getMessageOrBuilder();
          } else {
            return provider_ == null ?
                HeaderOuterClass.Provider.getDefaultInstance() : provider_;
          }
        }
        /**
         * <pre>
         * Publisher/Provider of the dataset.
         * </pre>
         *
         * <code>.Provider provider = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            HeaderOuterClass.Provider, HeaderOuterClass.Provider.Builder, HeaderOuterClass.ProviderOrBuilder> 
            getProviderFieldBuilder() {
          if (providerBuilder_ == null) {
            providerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                HeaderOuterClass.Provider, HeaderOuterClass.Provider.Builder, HeaderOuterClass.ProviderOrBuilder>(
                    getProvider(),
                    getParentForChildren(),
                    isClean());
            provider_ = null;
          }
          return providerBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }
  
        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }
  
  
        // @@protoc_insertion_point(builder_scope:Header)
      }
  
      // @@protoc_insertion_point(class_scope:Header)
      private static final HeaderOuterClass.Header DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new HeaderOuterClass.Header();
      }
  
      public static HeaderOuterClass.Header getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }
  
      private static final com.google.protobuf.Parser<Header>
          PARSER = new com.google.protobuf.AbstractParser<Header>() {
        @java.lang.Override
        public Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
        }
      };
  
      public static com.google.protobuf.Parser<Header> parser() {
        return PARSER;
      }
  
      @java.lang.Override
      public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
      }
  
      @java.lang.Override
      public HeaderOuterClass.Header getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }
  
    }
  
    public interface ProviderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Provider)
        com.google.protobuf.MessageOrBuilder {
  
      /**
       * <pre>
       * Unique identifier of the provider.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      java.lang.String getId();
      /**
       * <pre>
       * Unique identifier of the provider.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      com.google.protobuf.ByteString
          getIdBytes();
  
      /**
       * <pre>
       * Name of the provider.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <pre>
       * Name of the provider.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code Provider}
     */
    public static final class Provider extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Provider)
        ProviderOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Provider.newBuilder() to construct.
      private Provider(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Provider() {
        id_ = "";
        name_ = "";
      }
  
      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Provider();
      }
  
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Provider(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
  
                id_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
  
                name_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeaderOuterClass.internal_static_Provider_descriptor;
      }
  
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeaderOuterClass.internal_static_Provider_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeaderOuterClass.Provider.class, HeaderOuterClass.Provider.Builder.class);
      }
  
      public static final int ID_FIELD_NUMBER = 1;
      private volatile java.lang.Object id_;
      /**
       * <pre>
       * Unique identifier of the provider.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Unique identifier of the provider.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
  
      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <pre>
       * Name of the provider.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Name of the provider.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
  
      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;
  
        memoizedIsInitialized = 1;
        return true;
      }
  
      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        unknownFields.writeTo(output);
      }
  
      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;
  
        size = 0;
        if (!getIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }
  
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof HeaderOuterClass.Provider)) {
          return super.equals(obj);
        }
        HeaderOuterClass.Provider other = (HeaderOuterClass.Provider) obj;
  
        if (!getId()
            .equals(other.getId())) return false;
        if (!getName()
            .equals(other.getName())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }
  
      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }
  
      public static HeaderOuterClass.Provider parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderOuterClass.Provider parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderOuterClass.Provider parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderOuterClass.Provider parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderOuterClass.Provider parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderOuterClass.Provider parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderOuterClass.Provider parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static HeaderOuterClass.Provider parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static HeaderOuterClass.Provider parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static HeaderOuterClass.Provider parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static HeaderOuterClass.Provider parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static HeaderOuterClass.Provider parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
  
      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(HeaderOuterClass.Provider prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }
  
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Provider}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Provider)
          HeaderOuterClass.ProviderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return HeaderOuterClass.internal_static_Provider_descriptor;
        }
  
        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return HeaderOuterClass.internal_static_Provider_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  HeaderOuterClass.Provider.class, HeaderOuterClass.Provider.Builder.class);
        }
  
        // Construct using HeaderOuterClass.Provider.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
  
        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = "";
  
          name_ = "";
  
          return this;
        }
  
        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return HeaderOuterClass.internal_static_Provider_descriptor;
        }
  
        @java.lang.Override
        public HeaderOuterClass.Provider getDefaultInstanceForType() {
          return HeaderOuterClass.Provider.getDefaultInstance();
        }
  
        @java.lang.Override
        public HeaderOuterClass.Provider build() {
          HeaderOuterClass.Provider result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
  
        @java.lang.Override
        public HeaderOuterClass.Provider buildPartial() {
          HeaderOuterClass.Provider result = new HeaderOuterClass.Provider(this);
          result.id_ = id_;
          result.name_ = name_;
          onBuilt();
          return result;
        }
  
        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof HeaderOuterClass.Provider) {
            return mergeFrom((HeaderOuterClass.Provider)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
  
        public Builder mergeFrom(HeaderOuterClass.Provider other) {
          if (other == HeaderOuterClass.Provider.getDefaultInstance()) return this;
          if (!other.getId().isEmpty()) {
            id_ = other.id_;
            onChanged();
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }
  
        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }
  
        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          HeaderOuterClass.Provider parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (HeaderOuterClass.Provider) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
  
        private java.lang.Object id_ = "";
        /**
         * <pre>
         * Unique identifier of the provider.
         * </pre>
         *
         * <code>string id = 1;</code>
         * @return The id.
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Unique identifier of the provider.
         * </pre>
         *
         * <code>string id = 1;</code>
         * @return The bytes for id.
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Unique identifier of the provider.
         * </pre>
         *
         * <code>string id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
      throw new NullPointerException();
    }
    
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Unique identifier of the provider.
         * </pre>
         *
         * <code>string id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Unique identifier of the provider.
         * </pre>
         *
         * <code>string id = 1;</code>
         * @param value The bytes for id to set.
         * @return This builder for chaining.
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
      throw new NullPointerException();
    }
    checkByteStringIsUtf8(value);
          
          id_ = value;
          onChanged();
          return this;
        }
  
        private java.lang.Object name_ = "";
        /**
         * <pre>
         * Name of the provider.
         * </pre>
         *
         * <code>string name = 2;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Name of the provider.
         * </pre>
         *
         * <code>string name = 2;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Name of the provider.
         * </pre>
         *
         * <code>string name = 2;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
      throw new NullPointerException();
    }
    
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Name of the provider.
         * </pre>
         *
         * <code>string name = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Name of the provider.
         * </pre>
         *
         * <code>string name = 2;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
      throw new NullPointerException();
    }
    checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }
  
        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }
  
  
        // @@protoc_insertion_point(builder_scope:Provider)
      }
  
      // @@protoc_insertion_point(class_scope:Provider)
      private static final HeaderOuterClass.Provider DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new HeaderOuterClass.Provider();
      }
  
      public static HeaderOuterClass.Provider getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }
  
      private static final com.google.protobuf.Parser<Provider>
          PARSER = new com.google.protobuf.AbstractParser<Provider>() {
        @java.lang.Override
        public Provider parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Provider(input, extensionRegistry);
        }
      };
  
      public static com.google.protobuf.Parser<Provider> parser() {
        return PARSER;
      }
  
      @java.lang.Override
      public com.google.protobuf.Parser<Provider> getParserForType() {
        return PARSER;
      }
  
      @java.lang.Override
      public HeaderOuterClass.Provider getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }
  
    }
  
    private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_Header_descriptor;
    private static final 
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_Header_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_Provider_descriptor;
    private static final 
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_Provider_fieldAccessorTable;
  
    public static com.google.protobuf.Descriptors.FileDescriptor
        getDescriptor() {
      return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
        descriptor;
    static {
      java.lang.String[] descriptorData = {
        "\n\014Header.proto\"\274\001\n\006Header\022\017\n\007version\030\001 \001" +
        "(\t\022.\n\016incrementality\030\002 \001(\0162\026.Header.Incr" +
        "ementality\022\021\n\ttimestamp\030\003 \001(\004\022\033\n\010provide" +
        "r\030\004 \001(\0132\t.Provider\"A\n\016Incrementality\022\013\n\007" +
        "UNKNOWN\020\000\022\020\n\014FULL_DATASET\020\001\022\020\n\014DIFFERENT" +
        "IAL\020\002\"$\n\010Provider\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 " +
        "\001(\tb\006proto3"
      };
      descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
      internal_static_Header_descriptor =
        getDescriptor().getMessageTypes().get(0);
      internal_static_Header_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
          internal_static_Header_descriptor,
          new java.lang.String[] { "Version", "Incrementality", "Timestamp", "Provider", });
      internal_static_Provider_descriptor =
        getDescriptor().getMessageTypes().get(1);
      internal_static_Provider_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
          internal_static_Provider_descriptor,
          new java.lang.String[] { "Id", "Name", });
    }
  
    // @@protoc_insertion_point(outer_class_scope)
  }
  
